### ISSUE TITLE
Needs license

### ISSUE THREAD

**Issue by DarrenCook** [tensorfire/cyborg-writer#1]
This is great, and very similar to something I have been working on. I saw mention that TensorFire will be released under an MIT license? I assume the demos will be too, but could you add an explicit LICENSE file to confirm this? I need this before I can dive in and study your code.

(Or, if you can confirm MIT is the intention, I can do a pull request: in that case I will need to know who the copyright holder should be named as.)

**Comment by antimatter15** [comment]
Yeah it'll be under the MIT license. I've added one to this repo.
